//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Auction.Web.item {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtitem_name;
		protected global::System.Web.UI.WebControls.TextBox txtitem_remark;
		protected global::System.Web.UI.WebControls.TextBox txtitem_desc;
		protected global::System.Web.UI.WebControls.TextBox txtkind_id;
		protected global::System.Web.UI.WebControls.TextBox txtaddtime;
		protected global::System.Web.UI.WebControls.TextBox txtendtime;
		protected global::System.Web.UI.WebControls.TextBox txtinit_price;
		protected global::System.Web.UI.WebControls.TextBox txtmax_price;
		protected global::System.Web.UI.WebControls.TextBox txtowner_id;
		protected global::System.Web.UI.WebControls.TextBox txtwiner_id;
		protected global::System.Web.UI.WebControls.TextBox txtstate_id;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
