//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Auction.Web.item {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblitem_id;
	protected global::System.Web.UI.WebControls.Label lblitem_name;
	protected global::System.Web.UI.WebControls.Label lblitem_remark;
	protected global::System.Web.UI.WebControls.Label lblitem_desc;
	protected global::System.Web.UI.WebControls.Label lblkind_id;
	protected global::System.Web.UI.WebControls.Label lbladdtime;
	protected global::System.Web.UI.WebControls.Label lblendtime;
	protected global::System.Web.UI.WebControls.Label lblinit_price;
	protected global::System.Web.UI.WebControls.Label lblmax_price;
	protected global::System.Web.UI.WebControls.Label lblowner_id;
	protected global::System.Web.UI.WebControls.Label lblwiner_id;
	protected global::System.Web.UI.WebControls.Label lblstate_id;


       
    }
}
